name: beauty_queen
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  get: ^4.6.6
  http: ^1.1.0
  flutter_screenutil: ^5.9.0
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  google_maps_flutter: ^2.5.0
  map_launcher: ^3.1.0
  url_launcher: ^6.2.1

  # dio
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  firebase_performance_dio: ^0.4.1
  shared_preferences: ^2.2.2
  device_info_plus: ^9.1.1
  quiver: ^3.2.1
  loading_indicator: ^3.1.1
  easy_localization: ^3.0.3
  fl_country_code_picker: ^0.1.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/langs/
  fonts:
    - family: 'TheSansBold'
      fonts:
        - asset: assets/fonts/Bahij TheSansArabic Bold.ttf
    - family: 'TheSansLight'
      fonts:
        - asset: assets/fonts/TheSansArabic Light.ttf

