name: beauty_queen
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  get: ^4.6.6
  http: ^1.1.0
  flutter_screenutil: ^5.9.0
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  google_maps_flutter: ^2.5.0
  map_launcher: ^3.1.0
  url_launcher: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: 'TheSansBold'
      fonts:
        - asset: assets/fonts/Bahij TheSansArabic Bold.ttf
    - family: 'TheSansLight'
      fonts:
        - asset: assets/fonts/TheSansArabic Light.ttf

