import 'package:flutter/material.dart';

const kPinkColor = Color(0xFFDE0F7E);
const kGrayColor = Color(0xFF707070);
const klPinkColor = Color(0xFFF4C6DD);
const kOrangeColor = Color(0xFFFF4242);
const kPrimaryColor = Color(0xFFDE0F7E);
const kSecondaryColor = Color(0xFF2C3E50);
const kHintTextColor = Color(0xFFD5D5D5);
const kBorderColor = Color(0xFFD9DEE2);
const kDividerColor = Color(0xFFD8D8D8);
const kShadowColor = Color(0x42C6C6C6);
const kWhiteColor = Colors.white;
const kBlackColor = Colors.black;
const kTextGrayColor = Color(0xFFB8B8B8);
const kcontainerGrayColor = Color(0xFFF5F5F5);
const kTextBlackColor = Color(0xFF27292A);
const kTextDGColor = Color(0xFF717171);
const kCDGColor = Color(0xFFDEDEDE);
const kDividerrColor = Color(0xFFF4F4F4);
