// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl0ScbJK84QvFROKAHi-WRxvqNg43rzTU',
    appId: '1:636984093820:web:1951508f3244faa9282df9',
    messagingSenderId: '636984093820',
    projectId: 'beautyqueen-93be2',
    authDomain: 'beautyqueen-93be2.firebaseapp.com',
    storageBucket: 'beautyqueen-93be2.appspot.com',
    measurementId: 'G-5E4QP6C1P5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4SGyMVmRhMnCox2grhQMaRXpCwmyPRJY',
    appId: '1:636984093820:android:919f94285aaa3d7b282df9',
    messagingSenderId: '636984093820',
    projectId: 'beautyqueen-93be2',
    storageBucket: 'beautyqueen-93be2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCv6S6nD8pVh6ZL2CjUjIr_3sslEzg_V8',
    appId: '1:636984093820:ios:847bcfa40feec8ef282df9',
    messagingSenderId: '636984093820',
    projectId: 'beautyqueen-93be2',
    storageBucket: 'beautyqueen-93be2.appspot.com',
    androidClientId: '636984093820-b00p1rrdbssupnn415mq926t68vanobo.apps.googleusercontent.com',
    iosClientId: '636984093820-m8ecnbpcn4uvaqh1udal57q4srnt52mi.apps.googleusercontent.com',
    iosBundleId: 'com.beauty.beautyQueen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCv6S6nD8pVh6ZL2CjUjIr_3sslEzg_V8',
    appId: '1:636984093820:ios:528b10523a96dc76282df9',
    messagingSenderId: '636984093820',
    projectId: 'beautyqueen-93be2',
    storageBucket: 'beautyqueen-93be2.appspot.com',
    androidClientId: '636984093820-b00p1rrdbssupnn415mq926t68vanobo.apps.googleusercontent.com',
    iosClientId: '636984093820-htc70bu5jnnrn0hsop07mve4at39v2f9.apps.googleusercontent.com',
    iosBundleId: 'com.example.beautyQueen.RunnerTests',
  );
}
