# This is a basic workflow to help you get started with Actions

name: FlutterAndroidBuild

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - "*.*.*"

#    paths:
#      - 'pubspec.yaml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  android-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
          check-latest: true


      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.2

      - run: flutter --version

      - name: Downloading Dependencies (Pub Upgrade)
        run: flutter pub upgrade
      - run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build APK
        run: flutter build apk --release

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Upload to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

#      - name: Upload Artifact
#        uses: actions/upload-artifact@v3
#        with:
#          path: |
#            build/app/outputs/flutter-apk/app-release.apk
#            build/app/outputs/bundle/release/app-release.aab
